### ISSUE TITLE
Cannot find asset name when saving

### ISSUE THREAD

**Issue by Parzival-3141** [Tkachov/dat1_extractor#1]
I was trying to save a `.model` asset but got this error:
```
Traceback (most recent call last):
  File "server\api_utils.py", line 30, in json_api
  File "server\state\assets.py", line 35, in get_asset
AttributeError: 'State' object has no attribute '_get_asset_name_loc'
```
Taking a look at the code, it seems like it's trying to get the asset name to pass to the `send_file` flask method. If this method opens a save dialog, you could wrap line 35 in a try block and pass a default name if it fails, since the user could rename the file anyway.

**Comment by Tkachov** [comment]
Yeah, I've renamed the method, but forgot to rename usages. I've already fixed it in e653be0 -- commit that goes after 0.1.0. You can use the latest code (would require python3 with Flask installed) or wait for a next .exe release. Contact me on Discord if you need help setting up python.
