### ISSUE TITLE
extract_assets.py - Different decompressed size

### ISSUE THREAD

**Issue by 09williamsad** [Tkachov/dat1_extractor#16]
OS: Windows 11 Pro 23H2 22631.4169
Python: 3.12.5 64 bit
Script version/date: 2024-09-14
Game version: 2.618.0.0

Commands:
cd /d C:\Users\adamw\Downloads\Overdrive
python extract_assets.py "E:\RatchetClank" "E:\RatchetClank"

Error:
[!] Actual decompressed size 12574720 isn't equal to one written in the file 12574420
[!] Not a toc

**Comment by Tkachov** [comment]
From README:

> Contents of this repo are mostly for researchers, who can read the code, fix it if it doesn't work the way they want and write their own tools based on it.

This script works with `dat1lib.types.toc.TOC`. RCRA type is `dat1lib.types.toc2.TOC2`.

----

If you just wanted to extract assets, there are easier ways to do that: [Assets Browser](https://github.com/Tkachov/ALERT/wiki/Assets-Browser) or [Modding Tool](https://github.com/Tkachov/Overstrike/wiki/Modding-Tool%3A-Quickstart).
