### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by tetTris11** [Tkachov/dat1_extractor#3]
I'm attempting to rip from R&C-Rift Apart though when clicking on the server address it only highlights it as though it were just text and not a link.
I've tried with CTRL and shift.
I've also checked my anti-virus though that doesn't appear to be the issue.

Any potential info for this? thanks.
![Capture](https://github.com/Tkachov/dat1_extractor/assets/18501609/a2434ec4-518c-43f1-abed-cc2e4ca9b694)

**Comment by Tkachov** [comment]
Type this address in a browser manually, or copy the text (usually with a right click after you selected like on your screenshot) and paste there.

You can also type `localhost:55555`.
